spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/subscription-tracker}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    dev.michaelgoldman.subscriptiontrackerbackend: DEBUG
    org.springframework.jdbc.core: DEBUG   # see the SQL JdbcTemplate runs