spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    clean-disabled: true

logging:
  level:
    root: INFO
    dev.michaelgoldman.subscriptiontrackerbackend: INFO

  structured:
    format:
      console: ecs