// Copy & paste into dbdiagram.io to view or edit the diagram

Table subscriptions {
  id bigint [primary key, increment]
  name varchar(100) [unique, not null]
  price numeric(10,2) [not null]
}

Records subscriptions(id, name, price) {
  0, 'Netflix', 9.99
  1, 'HBO Max', 5.99
  2, 'Claude', 17.00
  3, 'Udemy', 32.00
}